({
  library(vroom)
  library(arrow)
  library(dplyr)
})
x <- vroom_arrow(file)
invisible(NULL)
print(x)
a <- head(x)
b <- tail(x)
c <- slice_sample(x, n = 100) |> compute()
d <- filter(x, X1 == "helpless_sheep") |> compute()
e <- group_by(x, X1) %>% summarise(n = n()) |> compute()
