({
  library(arrow)
  library(dplyr)
})
x <- read_delim_arrow(file, delim = "\t", as_data_frame = TRUE)
invisible(NULL)
print(x)
a <- head(x)
b <- tail(x)
c <- slice_sample(x, n = 100)
d <- filter(x, X1 > 3)
e <- group_by(x, as.integer(X2)) %>% summarise(avg_X1 = mean(X1))
