({
  library(vroom)
  library(arrow)
  library(dplyr)
})
x <- vroom_arrow(file)
invisible(NULL)
print(x)
a <- head(x)
b <- tail(x)
c <- slice_sample(x, n = 100) |> compute()
d <- filter(x, X1 > 3) |> compute()
e <- group_by(x, as.integer(X2)) %>% summarise(avg_X1 = mean(X1)) |> compute()
