({
  library(vroom)
  library(arrow)
  library(dplyr)
})
x <- vroom_arrow(file)
invisible(NULL)
print(x)
a <- head(x)
b <- tail(x)
c <- slice_sample(x, n = 100) |> compute()
d <- filter(x, X10 > 3) |> compute()
e <- group_by(x, X10) %>% summarise(avg = mean(X18)) |> compute()
